local Detours = XCF.Detours
local IsXCFContraption = XCF.IsXCFContraption

local function DetourE2(E2Sig)
    local Func Func = Detours.Expression2(E2Sig, function(Scope, Args, ...)
        if IsXCFContraption(Args[1]) then print("Detoured E2 function: " .. E2Sig) return end
        return Func(Scope, Args, ...)
    end)
end

DetourE2("applyAngForce(a)")
DetourE2("applyAngForce(b:a)")
DetourE2("applyAngForce(e:a)")
DetourE2("applyForce(b:v)")
DetourE2("applyForce(e:v)")
DetourE2("applyForce(v)")
DetourE2("applyOffsetForce(b:vv)")
DetourE2("applyOffsetForce(e:vv)")
DetourE2("applyOffsetForce(vv)")
DetourE2("propSetAngVelocity(e:v)")
DetourE2("propSetAngVelocityInstant(e:v)")
DetourE2("propSetBuoyancy(e:n)")
DetourE2("propSetElasticity(e:n)")
DetourE2("propSetFriction(e:n)")
DetourE2("propSetVelocity(e:v)")
DetourE2("propSetVelocityInstant(e:v)")
DetourE2("setAlpha(e:n)")
DetourE2("setAng(b:a)")
DetourE2("setAng(e:a)")
DetourE2("setAngVelocity(b:v)")
DetourE2("setAngVelocityInstant(b:v)")
DetourE2("setAngle(r:na)")
DetourE2("setBuoyancy(b:n)")
DetourE2("setCollisionGroup(e:n)")
DetourE2("setCollisions(b:n)")
DetourE2("setColor(e:nnn)")
DetourE2("setColor(e:nnnn)")
DetourE2("setColor(e:v)")
DetourE2("setColor(e:vn)")
DetourE2("setColor(e:xv4)")
DetourE2("setColor(nnn)")
DetourE2("setConstant(e:nn)")
DetourE2("setConstant(e:nnn)")
DetourE2("setDrag(b:n)")
DetourE2("setInertia(b:v)")
DetourE2("setLocalAng(e:a)")
DetourE2("setLocalPos(e:v)")
DetourE2("setMass(b:n)")
DetourE2("setMass(e:n)")
DetourE2("setMass(n)")
DetourE2("setMaterial(e:s)")
DetourE2("setPhysicalMaterial(b:s)")
DetourE2("setPos(b:v)")
DetourE2("setPos(e:v)")
DetourE2("setSubMaterial(e:ns)")
DetourE2("setVelocity(b:v)")
DetourE2("setVelocityInstant(b:v)")